#blockStream.delayBetweenBlockItems=3_000_000
#blockStream.folderRootPath=/Users/user/Downloads/block-0.0.3-perf1
#blockStream.managerImplementation=BlockAsFileLargeDataSets
#blockStream.maxBlockItemsToStream=100_000_000

#blockStream.delayBetweenBlockItems=2000000

# 7.2k block items per sec
#blockStream.delayBetweenBlockItems=100000

# 13.4k block items per sec
#blockStream.delayBetweenBlockItems=50000

# 24k block items per sec
#blockStream.delayBetweenBlockItems=25000

# 40k block items per sec
#blockStream.delayBetweenBlockItems=10000

#blockStream.delayBetweenBlockItems=8000

# 50k block items per sec - breaks around 8 mins
#blockStream.delayBetweenBlockItems=3000

# 65k block items/sec
#blockStream.delayBetweenBlockItems=1500

#blockStream.delayBetweenBlockItems=1000

# ~80k block items/sec - max limit
#blockStream.delayBetweenBlockItems=100
#blockStream.managerImplementation=DynamicBlockItemGenerator
#blockStream.streamingMode=CONSTANT_RATE
#blockStream.maxBlockItemsToStream=100_000_000
#blockStream.delayBetweenBlockItems=100

# 2 blocks/sec - 1 hr recording
#blockStream.millisecondsPerBlock=5000

blockStream.folderRootPath=/Users/mattpeterson/Downloads/BN_Test_Data/block-0.0.3
blockStream.managerImplementation=BlockAsFileLargeDataRange
blockStream.streamingMode=MILLIS_PER_BLOCK
blockStream.millisecondsPerBlock=50

