apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hedera-block-node.fullname" . }}
  labels:
    {{- include "hedera-block-node.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hedera-block-node.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hedera-block-node.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hedera-block-node.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.service.port }}
            protocol: TCP
        envFrom:
          - configMapRef:
              name: {{ include "hedera-block-node.fullname" . }}-config
          - secretRef:
              name: {{ include "hedera-block-node.fullname" . }}-secret

        # TODO: Uncomment them once we have the health and readiness probes in our application
        #livenessProbe:
        #  httpGet:
        #    path: /health # we need to define this in our application
        #    port: 8080 # will be the same as server port?
        #readinessProbe:
        #    httpGet:
        #      path: /ready # we need to define this in our application
        #      port: 8080 # will be the same as server port?
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

