{{- /*
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hedera-block-node.fullname" . }}-secret
type: Opaque
data:
{{- range $key, $value := .Values.blockNode.secret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
