apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hedera-block-node.fullname" . }}-secret
type: Opaque
data:
  PRIVATE_KEY_TYPE: {{ .Values.blockNode.consumer.privateKeyType | quote | b64enc }}
  PRIVATE_KEY_ENCODING: {{ .Values.blockNode.consumer.privateKeyEncoding | quote | b64enc }}
  PRIVATE_KEY_ACCOUNT_ID: {{ .Values.blockNode.consumer.privateKeyAccountId | quote | b64enc }}
  PRIVATE_KEY: {{ .Values.blockNode.consumer.privateKey | quote | b64enc }}
  HEDERA_NETWORK: {{ .Values.blockNode.consumer.hederaNetwork | quote | b64enc }}
