apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hedera-block-node.fullname" . }}
  labels:
    release: prometheus  # Should match the release name of kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: {{ include "hedera-block-node.name" . }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      interval: 15s
