global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'local'
    static_configs:
      - targets: ['block-node-server:9999', 'cadvisor:8080']

  - job_name: 'simulator-publisher'
    static_configs:
      - targets: ['simulator-publisher:9998']
    metrics_path: '/metrics'
    scheme: 'http'
    relabel_configs:
      - source_labels: [__name__]
        target_label: instance_type
        replacement: 'publisher'

  - job_name: 'simulator-consumer'
    static_configs:
      - targets: ['simulator-consumer:9997']
    metrics_path: '/metrics'
    scheme: 'http'
    relabel_configs:
      - source_labels: [__name__]
        target_label: instance_type
        replacement: 'consumer'
