global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'local'
    static_configs:
      - targets: ['block-node-server:9999', 'cadvisor:8080']

  - job_name: 'simulator-publisher'
    static_configs:
      - targets: ['host.docker.internal:9998']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'simulator-consumer'
    static_configs:
      - targets: ['host.docker.internal:9997']
    metrics_path: '/metrics'
    scheme: 'http'
