{
 "title": "Log Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Configuration Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container_name=\"block-node-server\"} |~ \"log\""
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container_name=\"block-node-server\"} |~ \"ERROR\""
    }
   ]
  },
  {
   "title": "Warning Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{container_name=\"block-node-server\"} |~ \"WARNING\""
    }
   ]
  }
 ]
}