
image:
  repository: ghcr.io/hashgraph/hedera-block-node/simulator-image
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

simulator:
  config:
    # either CONSUMER or PUBLISHER
    BLOCK_STREAM_SIMULATOR_MODE: "PUBLISHER"
    GRPC_SERVER_ADDRESS: "blkNod-block-node-helm-chart"
  secret:
    PRIVATE_KEY: "fake_private_key"
