services:
  block-node-server:
    container_name: block-node-server
    image: block-node-server:${VERSION}
    env_file:
      - ../build/.env
    ports:
      - "8080:8080"
      - "5005:5005"
      - "9999:9999"

  cadvisor:
    image: "gcr.io/cadvisor/cadvisor:v0.47.0"
    container_name: cadvisor
    ports:
      - "8081:8080" # Expose cAdvisor on port 8081
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    # Exposing Prometheus outside the stack can create issues with
    # the MetricsService in the Simulator. Here it's exposed within
    # the stack.
    ports:
      - "9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    volumes:
      - ./metrics/dashboards:/etc/grafana/provisioning/dashboards
      - ./metrics/datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
      - "3000:3000"

