{{- /*
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blockstream-simulator-chart.fullname" . }}-config
data:
  {{- range $key, $value := .Values.simulator.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
