# SPDX-License-Identifier: Apache-2.0
name: "PR Formatting Checks"
on:
  pull_request:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - reopened
      - edited
      - converted_to_draft
      - ready_for_review
      - review_requested
      - review_request_removed
      - locked
      - unlocked
      - synchronize

defaults:
  run:
    shell: bash

permissions:
  statuses: write

jobs:
  pr-formatting-checks:
    name: PR Formatting Checks
    runs-on: block-node-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: Check PR Title
        id: title-check
        uses: step-security/conventional-pr-title-action@19fb561b33015fd2184055a05ce5a3bcf2ba3f54 # v3.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Check Milestone
        run: |
          if [[ "${{ github.event.pull_request.milestone }}" == "" ]]; then
            echo "Milestone is not set. Setting failure."
            echo "MILESTONE_CHECK_FAILED=true" >> $GITHUB_ENV
          fi

      - name: Check Assignee
        run: |
          if [[ "${{ github.event.pull_request.assignees[0] }}" == "" ]]; then
            echo "Assignee is not set. Setting failure."
            echo "ASSIGNEE_CHECK_FAILED=true" >> $GITHUB_ENV
          fi

      - name: Check Labels
        run: |
          if [[ "${{ github.event.pull_request.labels[0] }}" == "" ]]; then
            echo "No labels are set. Setting failure."
            echo "LABEL_CHECK_FAILED=true" >> $GITHUB_ENV
          fi

      - name: Set Result for Title Check
        if: steps.title-check.outcome == 'failure'
        run: echo "TITLE_CHECK_FAILED=true" >> $GITHUB_ENV

      - name: Aggregate Results
        run: |
          failed=false
          if [ "${{ env.TITLE_CHECK_FAILED }}" == "true" ]; then
            echo "::error title=Title Check::❌ Title Check failed"
            failed=true
          else
            echo "::notice title=Title Check::✅ Title Check passed"
          fi
          if [ "${{ env.MILESTONE_CHECK_FAILED }}" == "true" ]; then
            echo "::error title=Milestone Check::❌ Milestone Check failed"
            failed=true
          else
            echo "::notice title=Milestone Check::✅ Milestone Check passed"
          fi
          if [ "${{ env.ASSIGNEE_CHECK_FAILED }}" == "true" ]; then
            echo "::error title=Assignee Check::❌ Assignee Check failed"
            failed=true
          else
            echo "::notice title=Assignee Check::✅ Assignee Check passed"
          fi
          if [ "${{ env.LABEL_CHECK_FAILED }}" == "true" ]; then
            echo "::error title=Label Check::❌ Label Check failed"
            failed=true
          else
            echo "::notice title=Label Check::✅ Label Check passed"
          fi
          if [ "$failed" == "true" ]; then
            exit 1
          fi
